import Head from "next/head";
import Image from "next/image";

// import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";
import Footer from "../components/footer";
import { Flex, Text, Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Flex
        as="header"
        maxW="full"
        p="20px"
        justifyContent="space-between"
        fontSize="0.875rem"
        lineHeight="1.25rem"
      >
        {/* left section */}
        <Flex alignItems="center" gap="16px">
          {/* variantat gadavaqcio */}
          <Text cursor="pointer" _hover={{ textDecoration: "underline" }}>
            About
          </Text>
          {/* variantat gadavaqcio */}
          <Text cursor="pointer" _hover={{ textDecoration: "underline" }}>
            Store
          </Text>
        </Flex>
        {/* right section */}
        <Flex alignItems="center" gap="16px">
          {/* variantat gadavaqcio */}
          <Text cursor="pointer" _hover={{ textDecoration: "underline" }}>
            Gmail
          </Text>
          {/* variantat gadavaqcio */}
          <Text cursor="pointer" _hover={{ textDecoration: "underline" }}>
            Images
          </Text>

          <Box
            as={ViewGridIcon}
            h="40px"
            w="40px"
            p="8px"
            cursor="pointer"
            borderRadius="9999px"
            _hover={{ backgroundColor: "#EDF2F7" }}
          />
        </Flex>
      </Flex>

      {/* Body */}
      <Flex
        as="form"
        flexDir="column"
        alignItems="center"
        //justifyContent="center"
        mt="176px"
        flexGrow={1}
        //w="80%"
      >
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          alt="Google background"
          height={100}
          width={300}
        />
        <Flex w="full" mt="20px" _hover={{ backgroundColor: "#EDF2F7" }}>
          <SearchIcon />
          <input type="text" />
          <MicrophoneIcon />
        </Flex>

        <Flex>
          <button>Googlee Search</button>
          <button>I'm Feeling lucky</button>
        </Flex>
      </Flex>

      {/* Footer */}
      <Footer />
    </div>
  );
}
